### ISSUE TITLE
Add doc reference for HIP-646

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-reference#130]
### Problem

HIP-646 introduces new protobuf fields. The new fields need to be supported in the SDKs. 

HIP: https://hips.hedera.com/hip/hip-646

### Solution

Document the API design for each SDK to add this feature.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1507
- [ ] https://github.com/hashgraph/hedera-sdk-js/issues/1736
- [ ] https://github.com/hashgraph/hedera-sdk-go/issues/777
- [ ] https://github.com/hashgraph/hedera-sdk-rust/issues/614
- [ ] https://github.com/hashgraph/hedera-sdk-swift/issues/168
- [ ] https://github.com/hashgraph/hedera-sdk-cpp/issues/445
```
