### ISSUE TITLE
Add doc reference HIP-765

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-reference#148]
### Problem

HIP: https://hips.hedera.com/hip/hip-765

Protobuf PR: https://github.com/hashgraph/hedera-protobufs/pull/313

This HIP proposes the addition of the metadata field to Non-Fungible Token Class, taking after the individual Non-Fungible Token (NFT) metadata field which was added in HIP-17. While HIP-17 metadata is scoped to a single NFT, here we propose adding metadata scoped to an entire token class.

```protobuf
TokenCreateTransactionBody
....
Metadata of the created token definition.
*/
bytes metadata = 23;
```

```protobuf
TokenUpdateTransactionBody
...
/**
* Metadata of the created token definition
*/
google.protobuf.BytesValue metadata = 16;
```

### Solution

Add setting and updating the token metadata field for NFTs. 

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1745
- [ ] https://github.com/hashgraph/hedera-sdk-js/issues/2188
- [ ] https://github.com/hashgraph/hedera-sdk-go/issues/885
- [ ] https://github.com/hashgraph/hedera-sdk-cpp/issues/674
```
